// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs6FiFDoOHYGifvwvkR7gSU616gmwvxvI',
    appId: '1:740523786640:web:bcac13db6c3048cb673315',
    messagingSenderId: '740523786640',
    projectId: 'secretaire-aje',
    authDomain: 'secretaire-aje.firebaseapp.com',
    storageBucket: 'secretaire-aje.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3PVDGVvmXcgKCBh0M99DsU8wfK5vgd4',
    appId: '1:740523786640:android:b4cf2021303513e3673315',
    messagingSenderId: '740523786640',
    projectId: 'secretaire-aje',
    storageBucket: 'secretaire-aje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDySGdA1Rk-flBAgycctVwE7SHx-B9tYRk',
    appId: '1:740523786640:ios:5b8037963c786420673315',
    messagingSenderId: '740523786640',
    projectId: 'secretaire-aje',
    storageBucket: 'secretaire-aje.firebasestorage.app',
    iosBundleId: 'bj.pentalightcode.secretaireAje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDySGdA1Rk-flBAgycctVwE7SHx-B9tYRk',
    appId: '1:740523786640:ios:5b8037963c786420673315',
    messagingSenderId: '740523786640',
    projectId: 'secretaire-aje',
    storageBucket: 'secretaire-aje.firebasestorage.app',
    iosBundleId: 'bj.pentalightcode.secretaireAje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs6FiFDoOHYGifvwvkR7gSU616gmwvxvI',
    appId: '1:740523786640:web:9c6a94d8a000088e673315',
    messagingSenderId: '740523786640',
    projectId: 'secretaire-aje',
    authDomain: 'secretaire-aje.firebaseapp.com',
    storageBucket: 'secretaire-aje.firebasestorage.app',
  );
}
